// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base_angular_speed`, `domino_type_to_u8`, `fall_threshold`, `normalize_domino_type`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

void resetWorld() => RustLib.instance.api.crateApiPhysicsResetWorld();

int placeDomino({
  required double x,
  required double y,
  required double angle,
  required int dominoType,
}) => RustLib.instance.api.crateApiPhysicsPlaceDomino(
  x: x,
  y: y,
  angle: angle,
  dominoType: dominoType,
);

int processCommands({required List<BridgePlaceDominoCmd> commands}) =>
    RustLib.instance.api.crateApiPhysicsProcessCommands(commands: commands);

bool triggerDominoPush() =>
    RustLib.instance.api.crateApiPhysicsTriggerDominoPush();

void step({required double deltaTime}) =>
    RustLib.instance.api.crateApiPhysicsStep(deltaTime: deltaTime);

void stepMultiple({required int steps, required double deltaTime}) => RustLib
    .instance
    .api
    .crateApiPhysicsStepMultiple(steps: steps, deltaTime: deltaTime);

List<DominoTransform> getDominoTransforms() =>
    RustLib.instance.api.crateApiPhysicsGetDominoTransforms();

List<BridgeEvent> getEvents() =>
    RustLib.instance.api.crateApiPhysicsGetEvents();

ChainStatus getChainStatus() =>
    RustLib.instance.api.crateApiPhysicsGetChainStatus();

double timeElapsed() => RustLib.instance.api.crateApiPhysicsTimeElapsed();

int dominoCount() => RustLib.instance.api.crateApiPhysicsDominoCount();

class BridgeEvent {
  final String kind;
  final int? dominoId;
  final double? x;
  final double? y;
  final double? angle;
  final double? timestamp;
  final int? totalDominoes;

  const BridgeEvent({
    required this.kind,
    this.dominoId,
    this.x,
    this.y,
    this.angle,
    this.timestamp,
    this.totalDominoes,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      dominoId.hashCode ^
      x.hashCode ^
      y.hashCode ^
      angle.hashCode ^
      timestamp.hashCode ^
      totalDominoes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          dominoId == other.dominoId &&
          x == other.x &&
          y == other.y &&
          angle == other.angle &&
          timestamp == other.timestamp &&
          totalDominoes == other.totalDominoes;
}

class BridgePlaceDominoCmd {
  final double x;
  final double y;
  final double angle;
  final int dominoType;

  const BridgePlaceDominoCmd({
    required this.x,
    required this.y,
    required this.angle,
    required this.dominoType,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ angle.hashCode ^ dominoType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlaceDominoCmd &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          angle == other.angle &&
          dominoType == other.dominoType;
}

class ChainStatus {
  final int dominoCount;
  final int fallenCount;
  final bool triggered;
  final bool completed;
  final double timeElapsed;

  const ChainStatus({
    required this.dominoCount,
    required this.fallenCount,
    required this.triggered,
    required this.completed,
    required this.timeElapsed,
  });

  @override
  int get hashCode =>
      dominoCount.hashCode ^
      fallenCount.hashCode ^
      triggered.hashCode ^
      completed.hashCode ^
      timeElapsed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChainStatus &&
          runtimeType == other.runtimeType &&
          dominoCount == other.dominoCount &&
          fallenCount == other.fallenCount &&
          triggered == other.triggered &&
          completed == other.completed &&
          timeElapsed == other.timeElapsed;
}

class DominoTransform {
  final int id;
  final double x;
  final double y;
  final double angle;
  final int dominoType;
  final bool isFallen;

  const DominoTransform({
    required this.id,
    required this.x,
    required this.y,
    required this.angle,
    required this.dominoType,
    required this.isFallen,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      x.hashCode ^
      y.hashCode ^
      angle.hashCode ^
      dominoType.hashCode ^
      isFallen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DominoTransform &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          x == other.x &&
          y == other.y &&
          angle == other.angle &&
          dominoType == other.dominoType &&
          isFallen == other.isFallen;
}

class PhysicsWorld {
  final List<SimDomino> dominoes;
  final List<BridgeEvent> events;
  final double elapsed;
  final int nextId;
  final bool triggered;
  final bool completed;

  const PhysicsWorld({
    required this.dominoes,
    required this.events,
    required this.elapsed,
    required this.nextId,
    required this.triggered,
    required this.completed,
  });

  static Future<PhysicsWorld> default_() =>
      RustLib.instance.api.crateApiPhysicsPhysicsWorldDefault();

  @override
  int get hashCode =>
      dominoes.hashCode ^
      events.hashCode ^
      elapsed.hashCode ^
      nextId.hashCode ^
      triggered.hashCode ^
      completed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhysicsWorld &&
          runtimeType == other.runtimeType &&
          dominoes == other.dominoes &&
          events == other.events &&
          elapsed == other.elapsed &&
          nextId == other.nextId &&
          triggered == other.triggered &&
          completed == other.completed;
}

class SimDomino {
  final int id;
  final double x;
  final double y;
  final double angle;
  final int dominoType;
  final bool isFallen;
  final double angularVelocity;

  const SimDomino({
    required this.id,
    required this.x,
    required this.y,
    required this.angle,
    required this.dominoType,
    required this.isFallen,
    required this.angularVelocity,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      x.hashCode ^
      y.hashCode ^
      angle.hashCode ^
      dominoType.hashCode ^
      isFallen.hashCode ^
      angularVelocity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimDomino &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          x == other.x &&
          y == other.y &&
          angle == other.angle &&
          dominoType == other.dominoType &&
          isFallen == other.isFallen &&
          angularVelocity == other.angularVelocity;
}
