// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Place a domino command
PlaceDominoCmd createPlaceDominoCmd({
  required double x,
  required double y,
  required double angle,
  required int dominoType,
}) => RustLib.instance.api.crateApiSimpleCreatePlaceDominoCmd(
  x: x,
  y: y,
  angle: angle,
  dominoType: dominoType,
);

/// Get domino type properties for UI display
(double, double) getDominoDimensions({required int dominoType}) => RustLib
    .instance
    .api
    .crateApiSimpleGetDominoDimensions(dominoType: dominoType);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PlaceDominoCmd>>
abstract class PlaceDominoCmd implements RustOpaqueInterface {}
