// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GameApi>>
abstract class GameApi implements RustOpaqueInterface {
  /// Drop an orb at the specified position
  void dropOrb({required double x, required double y, required int tier});

  factory GameApi() => RustLib.instance.api.crateApiSimpleGameApiNew();

  /// Step the physics simulation forward by delta_time seconds
  void stepPhysics({required double deltaTime});
}
